### ISSUE TITLE
Support URL-level (vs Host-level) storage locations

### ISSUE THREAD

**Issue by bnewbold** [datproject/dat-http#3]
From some quick experimentation and my reading of code, it looks like `dat-http` currently wants to connect to a host and request files from the root. Is there any strong reason not to allow the "host" to instead be a URL prefix, and have file requests come from relative locations?

Eg, to allow a dat to live at `https://www.some.tld/my-fancy-data/` (with a SLEEP directory at `https://www.some.tld/my-fancy-data/.dat`) instead of `https://my-fancy-data.some.tld`.

**Comment by max-mapper** [comment]
that should work okay, relevant line of code is:

```
return HTTPFile(url.resolve(host, filename))
```

so e.g. these both work

```
> var url = require('url')
undefined
> url.resolve('https://www.some.tld/my-fancy-data/', '.dat/content.metadata')
'https://www.some.tld/my-fancy-data/.dat/content.metadata'
> url.resolve('https://my-fancy-data.some.tld', '.dat/content.metadata')
'https://my-fancy-data.some.tld/.dat/content.metadata'

```

**Comment by bnewbold** [comment]
Indeed! Works for me now, I must have fat-fingered when testing earlier.
